name: contacts_flutter
description: get list contact native(android, ios)
version: 0.0.1
homepage: https://github.com/DoanpPhiHo/contacts_flutter

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.hodoan.contacts_flutter
        pluginClass: ContactsFlutterPlugin
      ios:
        pluginClass: ContactsFlutterPlugin